In [1]:
import numpy as np
import pandas as pd

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [3]:
train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
trainx=train.drop(['label'],axis=1)

In [5]:
trainy=train['label']

In [6]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
log_reg=LogisticRegression()
rnd_clf=RandomForestClassifier()
svm_clf=SVC()
dt_clf=DecisionTreeClassifier()

In [7]:
len(trainx)

42000

In [10]:
trainx.shape

(42000, 784)

In [12]:
voting_clf=VotingClassifier(estimators=[('lr',log_reg), ('rf', rnd_clf), ('svc', svm_clf), ('dt', dt_clf)], voting='hard')

In [13]:
vot=voting_clf.fit(trainx,trainy)

C:\Users\MAHENDER\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn = KNeighborsClassifier(n_neighbors=10)

In [16]:
knn.fit(trainx,trainy)

KNeighborsClassifier(n_neighbors=10)

In [18]:
prediction=knn.predict(test)

In [19]:
prediction

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [20]:
df=pd.DataFrame(prediction)

In [21]:
df.head()

   0
0  2
1  0
2  9
3  4
4  3

In [22]:
df.to_csv("solution.csv")