In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("data.csv",header=0)

In [3]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [4]:
from sklearn.preprocessing import LabelEncoder
data.ocean_proximity=LabelEncoder().fit_transform(data.ocean_proximity)

test.dropna(how='any',inplace=True,axis=1)

In [5]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
from sklearn.model_selection import train_test_split
train,test = train_test_split(data, test_size=0.33, random_state=42)

In [10]:
train.dropna(how='any',inplace=True,axis=1)

C:\Users\DELL\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [12]:
test.head()

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,median_house_value,ocean_proximity
20046,-119.01,36.06,25.0,1505.0,1392.0,359.0,1.6812,47700.0,1
3024,-119.46,35.14,30.0,2943.0,1565.0,584.0,2.5313,45800.0,1
15663,-122.44,37.80,52.0,3830.0,1310.0,963.0,3.4801,500001.0,3
20484,-118.72,34.28,17.0,3051.0,1705.0,495.0,5.7376,218600.0,0
9814,-121.93,36.62,34.0,2351.0,1063.0,428.0,3.7250,278000.0,4

In [6]:
train_x=train.drop(columns=['median_house_value'],axis=1)
test_x=test.drop(columns=['median_house_value'],axis=1)
train_y=train['median_house_value']
test_y=test['median_house_value']

In [8]:
mdd=model.fit(train_x,train_y)

In [9]:
predict_test = model.predict(test_x)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [12]:
testx.head()

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,ocean_proximity
20046,-119.01,36.06,25.0,1505.0,1392.0,359.0,1.6812,1
3024,-119.46,35.14,30.0,2943.0,1565.0,584.0,2.5313,1
15663,-122.44,37.80,52.0,3830.0,1310.0,963.0,3.4801,3
20484,-118.72,34.28,17.0,3051.0,1705.0,495.0,5.7376,0
9814,-121.93,36.62,34.0,2351.0,1063.0,428.0,3.7250,4

In [11]:
trainx.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
5088,-118.28,33.98,19.0,883.0,313.0,726.0,277.0,0.9809,0
17096,-122.23,37.46,33.0,2643.0,464.0,1015.0,427.0,4.2232,4
5617,-118.26,33.79,42.0,1162.0,264.0,1044.0,241.0,3.5488,0
20060,-119.26,35.87,24.0,1590.0,390.0,1686.0,372.0,1.6469,1
895,-121.96,37.54,14.0,5106.0,1207.0,2738.0,1108.0,3.9909,0

In [5]:
data.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'