In [36]:
import numpy as np

In [37]:
import pandas as pd

In [38]:
train=pd.read_csv('train.csv')

In [39]:
test=pd.read_csv('test.csv')

In [40]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [41]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [42]:
train=train.drop(['Name','Ticket','Age','Fare','Cabin'],axis=1)

In [43]:
test=test.drop(['Name','Ticket','Age','Fare','Cabin'],axis=1)

In [44]:
train.head()

   PassengerId  Survived  Pclass     Sex  SibSp  Parch Embarked
0            1         0       3    male      1      0        S
1            2         1       1  female      1      0        C
2            3         1       3  female      0      0        S
3            4         1       1  female      1      0        S
4            5         0       3    male      0      0        S

In [45]:
from sklearn.preprocessing import LabelEncoder
train.Sex=LabelEncoder().fit_transform(train.Sex)
train.Embarked=LabelEncoder().fit_transform(train.Embarked)
test.Sex=LabelEncoder().fit_transform(test.Sex)
test.Embarked=LabelEncoder().fit_transform(test.Embarked)

In [46]:
train.head()

   PassengerId  Survived  Pclass  Sex  SibSp  Parch  Embarked
0            1         0       3    1      1      0         2
1            2         1       1    0      1      0         0
2            3         1       3    0      0      0         2
3            4         1       1    0      1      0         2
4            5         0       3    1      0      0         2

In [47]:
test.head()

   PassengerId  Pclass  Sex  SibSp  Parch  Embarked
0          892       3    1      0      0         1
1          893       3    0      1      0         2
2          894       2    1      0      0         1
3          895       3    1      0      0         2
4          896       3    0      1      1         2

In [48]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
log_reg=LogisticRegression()
rnd_clf=RandomForestClassifier()
svm_clf=SVC()
dt_clf=DecisionTreeClassifier()

In [49]:
train=train.dropna()

In [50]:
test=test.dropna()

In [62]:
test.head()

   PassengerId  Pclass  Sex  SibSp  Parch  Embarked
0          892       3    1      0      0         1
1          893       3    0      1      0         2
2          894       2    1      0      0         1
3          895       3    1      0      0         2
4          896       3    0      1      1         2

In [51]:
trainx=train.drop(['Survived'],axis=1)

In [53]:
trainy=train['Survived']

In [54]:
trainx

     PassengerId  Pclass  Sex  SibSp  Parch  Embarked
0              1       3    1      1      0         2
1              2       1    0      1      0         0
2              3       3    0      0      0         2
3              4       1    0      1      0         2
4              5       3    1      0      0         2
..           ...     ...  ...    ...    ...       ...
886          887       2    1      0      0         2
887          888       1    0      0      0         2
888          889       3    0      1      2         2
889          890       1    1      0      0         0
890          891       3    1      0      0         1

[891 rows x 6 columns]

In [55]:
trainy

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [56]:
len(trainx)

891

In [57]:
len(trainy)

891

In [58]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
voting_clf=VotingClassifier(estimators=[('lr',log_reg), ('rf', rnd_clf), ('svc', svm_clf), ('dt', dt_clf)], voting='hard')

In [59]:
vot=voting_clf.fit(trainx,trainy)

In [60]:
prediction=vot.predict(test)

In [66]:
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
      dtype=int64)

In [73]:
df = pd.DataFrame(prediction)

In [74]:
df.head()

   0
0  0
1  0
2  0
3  0
4  0

In [67]:
test.head()

   PassengerId  Pclass  Sex  SibSp  Parch  Embarked
0          892       3    1      0      0         1
1          893       3    0      1      0         2
2          894       2    1      0      0         1
3          895       3    1      0      0         2
4          896       3    0      1      1         2

In [70]:
ans=test.drop(['Pclass','Sex','SibSp','Parch','Embarked'],axis=1)

In [79]:
ans.head()

   PassengerId
0          892
1          893
2          894
3          895
4          896

In [83]:
df.rename(columns={'0':'Survived'},inplace=True)

In [87]:
ans['Survived']=df

In [88]:
ans.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [89]:
ans

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [95]:
ans.to_csv("solution.csv")